/**
 * ==============================================================================================
 * NOTIFICATION DOMAIN MODEL
 * ==============================================================================================
 * Represents in-app alert events generated by the GoF Observer Pattern on the backend.
 */

export enum NotificationType {
  TICKET_ASSIGNED = 'TICKET_ASSIGNED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  NEW_MESSAGE = 'NEW_MESSAGE',
  SLA_BREACH = 'SLA_BREACH'
}

export interface NotificationItem {
  id: number;
  title: string;
  message: string;
  type: NotificationType;
  ticketId: number;
  read: boolean;
  createdAt: string;
}

export interface UnreadCountResponse {
  unreadCount: number;
}
