import { HttpInterceptorFn, HttpErrorResponse } from '@angular/common/http';
import { inject } from '@angular/core';
import { Router } from '@angular/router';
import { catchError, throwError } from 'rxjs';
import { ToastService } from '../services/toast.service';

/**
 * ==============================================================================================
 * HTTP INTERCEPTOR: ErrorInterceptor
 * ==============================================================================================
 * 
 * WHY THIS IS USED (Enterprise Client Observability & Error Handling):
 * 1. Global Error Translation: Intercepts failed HTTP responses and unpacks standardized
 *    RFC 7807 ErrorResponse payloads generated by Spring Boot's GlobalExceptionHandler.
 * 2. Proactive User Feedback: Dispatches user-friendly toast notifications for 400 Bad Request,
 *    403 Forbidden, 404 Not Found, 409 Conflict, 500 Server Error, and offline states.
 * 3. Graceful Auth Invalidation: Seamlessly cleans session state and routes to login on 401.
 */
export const errorInterceptor: HttpInterceptorFn = (req, next) => {
  const toastService = inject(ToastService);
  const router = inject(Router);

  return next(req).pipe(
    catchError((error: HttpErrorResponse) => {
      let errorMessage = 'An unexpected network error occurred.';

      if (error.error) {
        if (typeof error.error === 'string') {
          errorMessage = error.error;
        } else if (error.error.message) {
          errorMessage = error.error.message;
        }
      }

      // Handle specific HTTP Status Codes
      switch (error.status) {
        case 0:
          toastService.error('Cannot connect to backend server. Verify network connection.', 'Connection Lost');
          break;

        case 400:
          // Check for structured field-level validation errors
          if (error.error?.fieldErrors && Array.isArray(error.error.fieldErrors) && error.error.fieldErrors.length > 0) {
            const firstFieldError = error.error.fieldErrors[0];
            toastService.warning(`${firstFieldError.field}: ${firstFieldError.message}`, 'Validation Warning');
          } else {
            toastService.warning(errorMessage, 'Invalid Request');
          }
          break;

        case 401:
          // Only show toast and redirect if not already on the login page
          if (!req.url.includes('/api/auth/login')) {
            toastService.warning('Your session has expired. Please sign in again.', 'Session Expired');
            localStorage.removeItem('tix-token');
            localStorage.removeItem('tix-user');
            router.navigate(['/auth/login']);
          }
          break;

        case 403:
          toastService.error('You do not have permission to access this resource or perform this action.', 'Access Forbidden');
          break;

        case 404:
          toastService.error(errorMessage || 'The requested resource was not found.', 'Not Found');
          break;

        case 409:
          toastService.warning(errorMessage || 'A resource with these details already exists.', 'Conflict');
          break;

        case 500:
        case 502:
        case 503: {
          const correlationId = error.headers?.get('X-Correlation-ID') || error.headers?.get('x-correlation-id');
          const ref = correlationId ? ` (Ref: ${correlationId.substring(0, 8)})` : '';
          toastService.error(`The server encountered an error. Our engineering team has been notified.${ref}`, 'Server Error');
          break;
        }

        default: {
          const correlationId = error.headers?.get('X-Correlation-ID') || error.headers?.get('x-correlation-id');
          const ref = correlationId ? ` (Ref: ${correlationId.substring(0, 8)})` : '';
          toastService.error(`${errorMessage}${ref}`, `HTTP ${error.status}`);
          break;
        }
      }

      return throwError(() => error);
    })
  );
};
