package com.support.controller;

import com.support.config.GlobalExceptionHandler;
import com.support.dto.NotificationResponse;
import com.support.entity.NotificationType;
import com.support.security.JwtService;
import com.support.service.NotificationService;
import com.support.util.SecurityUtils;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.context.annotation.Import;
import org.springframework.http.MediaType;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.test.web.servlet.MockMvc;

import java.time.LocalDateTime;
import java.util.List;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * ==============================================================================================
 * AUTOMATED TESTING SUITE: NotificationController WebMvc Slice Test
 * ==============================================================================================
 * Tests the REST API endpoints exposing in-app notifications generated by the Observer Pattern.
 */
@WebMvcTest(controllers = NotificationController.class)
@AutoConfigureMockMvc(addFilters = false)
@Import(GlobalExceptionHandler.class)
class NotificationControllerTest {

    @Autowired
    private MockMvc mockMvc;


    @MockBean
    private NotificationService notificationService;

    @MockBean
    private SecurityUtils securityUtils;

    @MockBean
    private JwtService jwtService;

    @MockBean
    private UserDetailsService userDetailsService;

    @Test
    @DisplayName("GET /api/notifications - should return notifications for authenticated user")
    void testGetMyNotifications() throws Exception {
        when(securityUtils.resolveUserId(any())).thenReturn(10L);

        NotificationResponse response = NotificationResponse.builder()
                .id(1L)
                .title("Ticket Assigned: #100")
                .message("You were assigned to ticket 'Database timeout'")
                .type(NotificationType.TICKET_ASSIGNED)
                .ticketId(100L)
                .read(false)
                .createdAt(LocalDateTime.now())
                .build();

        when(notificationService.getNotificationsForUser(10L)).thenReturn(List.of(response));

        mockMvc.perform(get("/api/notifications")
                        .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$[0].id").value(1L))
                .andExpect(jsonPath("$[0].title").value("Ticket Assigned: #100"))
                .andExpect(jsonPath("$[0].type").value("TICKET_ASSIGNED"))
                .andExpect(jsonPath("$[0].read").value(false));

        verify(notificationService).getNotificationsForUser(10L);
    }

    @Test
    @DisplayName("GET /api/notifications/unread-count - should return unread badge count")
    void testGetUnreadCount() throws Exception {
        when(securityUtils.resolveUserId(any())).thenReturn(10L);
        when(notificationService.getUnreadCount(10L)).thenReturn(5L);

        mockMvc.perform(get("/api/notifications/unread-count")
                        .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.unreadCount").value(5));

        verify(notificationService).getUnreadCount(10L);
    }

    @Test
    @DisplayName("PUT /api/notifications/{id}/read - should mark notification as read")
    void testMarkAsRead() throws Exception {
        when(securityUtils.resolveUserId(any())).thenReturn(10L);

        NotificationResponse updated = NotificationResponse.builder()
                .id(1L)
                .title("Ticket Assigned: #100")
                .read(true)
                .build();

        when(notificationService.markAsRead(eq(1L), eq(10L))).thenReturn(updated);

        mockMvc.perform(put("/api/notifications/1/read")
                        .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.id").value(1L))
                .andExpect(jsonPath("$.read").value(true));

        verify(notificationService).markAsRead(1L, 10L);
    }

    @Test
    @DisplayName("PUT /api/notifications/read-all - should mark all notifications as read")
    void testMarkAllAsRead() throws Exception {
        when(securityUtils.resolveUserId(any())).thenReturn(10L);

        mockMvc.perform(put("/api/notifications/read-all")
                        .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk());

        verify(notificationService).markAllAsRead(10L);
    }
}
